import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-ford',
  templateUrl: './ford.component.html',
  styleUrls: ['./ford.component.scss']
})
export class FordComponent implements OnInit {



  selectedStatus =  {name: 'Select Status', code: 'select'};
  selectedDivision =  {name: 'Select Status', code: 'select'};

  columns: any[] = [];
  rows: any[] = [];
  response: any;
  statuses = [
    {name: 'Select Status', code: 'select'},
    {name: 'Active', code: 'active'},
    {name: 'In Active', code: 'inactive'},
  ];
  divisions = [
    {name: 'Select Division', code: 'select'},
    {name: 'All', code: 'all'},
    {name: 'DTTP', code: 'dttp'},
    {name: 'SR', code: 'sr'},
  ];

  data = mockData;

  constructor() {
    this.response = dummyData;
    this.columns = dummyData.result.columns.map(value =>value.key);
    this.rows = dummyData.result.rows;
    console.log(this.columns);
  }

  ngOnInit(): void {
  }

}
export const dummyData =
  {
    result: {
      rows: [
        "ordable_congigs",
        "sales_Codes",
        "sales",
        "purchases",
        "bod"
      ],
      columns: [
        {
          key: "Total F-150",
          values: [1, 2, 4, 8, 66]
        },
        {
          key: "Total A-150",
          values: [1, 2, 8, 8, 55]
        },
        {
          key: "Total C-150",
          values: [1, 2, 9, 8, 33],
        },

        {
          key: "Total Z-150",
          values: [1, 2, 9, 8, 33],
        }
      ]
    }
  };

      export const mockData = [
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR5        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "ABC        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "DTTP2        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "DTTP        ",
    "createdte": null
  }
  ,{
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR2        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR1        ",
    "createdte": null
  }
]
