import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-view-inquire',
  templateUrl: './view-inquire.component.html',
  styleUrls: ['./view-inquire.component.scss']
})
export class ViewInquireComponent implements OnInit {


  selectedStatus =  {name: 'Select Status', code: 'select'};
  selectedDivision =  {name: 'Select Status', code: 'select'};

  statuses = [
    {name: 'Select Status', code: 'select'},
    {name: 'Active', code: 'active'},
    {name: 'In Active', code: 'inactive'},
  ];
  divisions = [
    {name: 'Select Division', code: 'select'},
    {name: 'All', code: 'all'},
    {name: 'DTTP', code: 'dttp'},
    {name: 'SR', code: 'sr'},
  ];

  data = mockData;

  constructor() { }

  ngOnInit(): void {
  }

}
export const mockData = [
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR5        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "ABC        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "DTTP2        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "DTTP        ",
    "createdte": null
  }
  ,{
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR2        ",
    "createdte": null
  },
  {
    "id": 117,
    "companyLegalNm": "                    ",
    "businessNm": "test                ",
    "businessPh": "test        ",
    "businessEm": "test                ",
    "businessActType": "test                ",
    "businessAct": "test                ",
    "businessFx": "test                ",
    "ownerNm": "test                ",
    "ownerPh": "test        ",
    "ownerEm": "test                ",
    "ownerFx": "test                ",
    "addrLine1": "test                ",
    "addrLine2": "test                ",
    "city": "test                ",
    "country": "test                ",
    "caState": "test                ",
    "zipCode": "test  ",
    "busiAddrLine1": "test                ",
    "busiAddrLine2": "test                ",
    "busiCity": "test                ",
    "busiCountry": "test                ",
    "busiState": "test                ",
    "busiZipcode": "test  ",
    "dealerInfo2018HVACPurchases": "test      ",
    "dealerInfo2018YorkPurchases": "test      ",
    "dealerInfo2018TotalYorkPurchases": "test      ",
    "dealerInfo2019YorkPurchases": "test      ",
    "hvacPrimaryBrand": "test                ",
    "hvacSecondaryBrand": "test                ",
    "hvacOther": "test                ",
    "businessMixResidentialReplacement": null,
    "businessMixResidentialNewConstruction": "test                ",
    "businessMixCommercial": "test                ",
    "purchaseRequired": "test                ",
    "licenseAccept": "test                ",
    "epaCertificationTo": "test                ",
    "epaCertification": "test                ",
    "notValidEPA": "test                ",
    "epaExpirationDate": "test              ",
    "contractorsLicense": "test                ",
    "contractorsExpirationDate": "test              ",
    "additionalEmailNotification": "test                ",
    "status": "pending        ",
    "branchNumber": null,
    "brRegion": "yr        ",
    "brDivision": "SR1        ",
    "createdte": null
  }
]
